ARG ES_VERSION=9.5.4
FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
COPY --chown=elasticsearch:elasticsearch target/package-image/ /usr/share/elasticsearch/plugins/analysis-dynamic-synonym/
